### PR TITLE
Honor apache_listen_ip var on Debian setups.

### LINKED ISSUE #17: apache_listen_ip var is not honored in Debian setups.
On Debian setups the variable ```apache_listen_ip``` is not used when configuring ports.conf.

See vars/apache-24.yml, where a regexp is used to replace configuration with this pattern:

```  line: "Listen {{ apache_listen_port }}```

No ```apache_listen_ip``` variable used.

### PR DESCRIPTION
**Pull request by rsanzante**
This PR tries to address https://github.com/wcm-io-devops/ansible-role-apache/issues/17.

Added ```apache_listen_ip``` variable to the replacing line and support this change on the regexp pattern.

### CODE REVIEW

**Comment by rsanzante** [comment]
Not sure the error is related to my changes.

It says:

```ERROR: Failed to pre-validate.
{'lint': ['must be of string type']}
The command "molecule test" exited with 1.
```

But it seems is about this file: https://github.com/wcm-io-devops/ansible-role-apache/blob/master/molecule/default/molecule.yml

**Comment by tobias-richter** [comment]
@rsanzante thanks for your contribution! I have merged with the upstream (https://github.com/geerlingguy/ansible-role-apache) and this seemed to be an issue with the molecule tests. Can you please merge your branch with the latest master? I assume that the build will then succeed.

**Review by tobias-richter — CHANGES_REQUESTED** [review]
Please update your PR with the latest changes from wcm-io-devops:master

**Comment by rsanzante** [comment]
Hi, thanks for the reviewing. I've merged your master branch and now tests pass :)

**Review by tobias-richter — APPROVED** [review]

**Review by tobias-richter — APPROVED** [review]

**Comment by tobias-richter** [comment]
@rsanzante thanks for your contribution. I will release the role in a new version soon.

**Pull request merged**
